version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports: [ "5432:5432" ]
    volumes: [ "pg:/var/lib/postgresql/data" ]

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
  api:
    build: .
    depends_on: [ db ]
    command: pnpm run start
    volumes:
      - .:/app
      - /app/node_modules
    platform: linux/amd64
    environment:
      DATABASE_URL: postgres://app:app@db:5432/appdb
      PORT: 5600
      RUN_MIGRATIONS: 1
    ports: [ "5600:5600" ]

volumes:
  pg:
